-- Library Management System Database Setup (Improved)
-- Run this file in phpMyAdmin or MySQL command line

-- 1. Create users table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'student') NOT NULL
);

-- 2. Create books table
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    book_id VARCHAR(30) UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    published_year INT NOT NULL,
    genre VARCHAR(100),
    status ENUM('Available', 'Borrowed', 'Archived') DEFAULT 'Available',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create borrowed_books table
CREATE TABLE IF NOT EXISTS borrowed_books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    book_id INT NOT NULL,
    borrow_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    fine DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

-- 4. Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_books_status ON books(status);
CREATE INDEX IF NOT EXISTS idx_borrowed_books_user ON borrowed_books(user_id);
CREATE INDEX IF NOT EXISTS idx_borrowed_books_return_date ON borrowed_books(return_date);

-- 5. Insert default admin user (username: admin, password: admin123)
-- Password hash generated by password_hash('admin123', PASSWORD_BCRYPT)
INSERT INTO users (first_name, last_name, email, phone, username, password, role)
SELECT
    tmp.first_name,
    tmp.last_name,
    tmp.email,
    tmp.phone,
    tmp.username,
    tmp.password,
    tmp.role
FROM (
    SELECT
        'Admin' AS first_name,
        'User' AS last_name,
        'admin@example.com' AS email,
        '1234567890' AS phone,
        'admin' AS username,
        '$2y$10$NyNwm3BxlElH90Knqdvh4.rPBU.WAzq/uoGScd7GkG5OH.V/od/1e' AS password,
        'admin' AS role
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'admin'
)
LIMIT 1;

-- 6. Insert sample books (50 books)
INSERT IGNORE INTO books (book_id, title, author, published_year, genre, status) VALUES
('THJAN102024-FIC00001', 'The Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasy', 'Available'),
('LOTJAN102024-FIC00002', 'The Lord of the Rings', 'J.R.R. Tolkien', 1954, 'Fantasy', 'Available'),
('HARJAN102024-FIC00003', 'Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 1997, 'Fantasy', 'Available'),
('HARJAN102024-FIC00004', 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 1998, 'Fantasy', 'Available'),
('HARJAN102024-FIC00005', 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 1999, 'Fantasy', 'Available'),
('HARJAN102024-FIC00006', 'Harry Potter and the Goblet of Fire', 'J.K. Rowling', 2000, 'Fantasy', 'Available'),
('HARJAN102024-FIC00007', 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 2003, 'Fantasy', 'Available'),
('HARJAN102024-FIC00008', 'Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 2005, 'Fantasy', 'Available'),
('HARJAN102024-FIC00009', 'Harry Potter and the Deathly Hallows', 'J.K. Rowling', 2007, 'Fantasy', 'Available'),
('GOTJAN102024-FIC00010', 'A Game of Thrones', 'George R.R. Martin', 1996, 'Fantasy', 'Available'),
('GOTJAN102024-FIC00011', 'A Clash of Kings', 'George R.R. Martin', 1998, 'Fantasy', 'Available'),
('GOTJAN102024-FIC00012', 'A Storm of Swords', 'George R.R. Martin', 2000, 'Fantasy', 'Available'),
('GOTJAN102024-FIC00013', 'A Feast for Crows', 'George R.R. Martin', 2005, 'Fantasy', 'Available'),
('GOTJAN102024-FIC00014', 'A Dance with Dragons', 'George R.R. Martin', 2011, 'Fantasy', 'Available'),
('PRNJAN102024-FIC00015', 'The Princess Bride', 'William Goldman', 1973, 'Fantasy', 'Available'),
('WIZJAN102024-FIC00016', 'The Wizard of Earthsea', 'Ursula K. Le Guin', 1968, 'Fantasy', 'Available'),
('WIZJAN102024-FIC00017', 'The Tombs of Atuan', 'Ursula K. Le Guin', 1971, 'Fantasy', 'Available'),
('WIZJAN102024-FIC00018', 'The Farthest Shore', 'Ursula K. Le Guin', 1972, 'Fantasy', 'Available'),
('WIZJAN102024-FIC00019', 'Tehanu', 'Ursula K. Le Guin', 1990, 'Fantasy', 'Available'),
('WIZJAN102024-FIC00020', 'The Other Wind', 'Ursula K. Le Guin', 2001, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00021', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 1950, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00022', 'The Chronicles of Narnia: Prince Caspian', 'C.S. Lewis', 1951, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00023', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'C.S. Lewis', 1952, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00024', 'The Chronicles of Narnia: The Silver Chair', 'C.S. Lewis', 1953, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00025', 'The Chronicles of Narnia: The Horse and His Boy', 'C.S. Lewis', 1954, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00026', 'The Chronicles of Narnia: The Magician''s Nephew', 'C.S. Lewis', 1955, 'Fantasy', 'Available'),
('CHRJAN102024-FIC00027', 'The Chronicles of Narnia: The Last Battle', 'C.S. Lewis', 1956, 'Fantasy', 'Available'),
('DUNJAN102024-FIC00028', 'The Dunwich Horror', 'H.P. Lovecraft', 1929, 'Horror', 'Available'),
('CALJAN102024-FIC00029', 'The Call of Cthulhu', 'H.P. Lovecraft', 1928, 'Horror', 'Available'),
('SHIJAN102024-FIC00030', 'The Shadow over Innsmouth', 'H.P. Lovecraft', 1936, 'Horror', 'Available'),
('ATJAN102024-FIC00031', 'At the Mountains of Madness', 'H.P. Lovecraft', 1936, 'Horror', 'Available'),
('COUJAN102024-FIC00032', 'The Count of Monte Cristo', 'Alexandre Dumas', 1844, 'Adventure', 'Available'),
('THRJAN102024-FIC00033', 'The Three Musketeers', 'Alexandre Dumas', 1844, 'Adventure', 'Available'),
('ROBJAN102024-FIC00034', 'Robinson Crusoe', 'Daniel Defoe', 1719, 'Adventure', 'Available'),
('TREJAN102024-FIC00035', 'Treasure Island', 'Robert Louis Stevenson', 1883, 'Adventure', 'Available'),
('KIDJAN102024-FIC00036', 'Kidnapped', 'Robert Louis Stevenson', 1886, 'Adventure', 'Available'),
('SWIJAN102024-FIC00037', 'Swiss Family Robinson', 'Johann David Wyss', 1812, 'Adventure', 'Available'),
('GULJAN102024-FIC00038', 'Gulliver''s Travels', 'Jonathan Swift', 1726, 'Adventure', 'Available'),
('JULJAN102024-FIC00039', 'Julius Caesar', 'William Shakespeare', 1599, 'Drama', 'Available'),
('HAMJAN102024-FIC00040', 'Hamlet', 'William Shakespeare', 1603, 'Drama', 'Available'),
('MACJAN102024-FIC00041', 'Macbeth', 'William Shakespeare', 1606, 'Drama', 'Available'),
('ROMEJAN102024-FIC00042', 'Romeo and Juliet', 'William Shakespeare', 1597, 'Drama', 'Available'),
('OTHEJAN102024-FIC00043', 'Othello', 'William Shakespeare', 1603, 'Drama', 'Available'),
('KINGJAN102024-FIC00044', 'King Lear', 'William Shakespeare', 1606, 'Drama', 'Available'),
('TEMJAN102024-FIC00045', 'The Tempest', 'William Shakespeare', 1611, 'Drama', 'Available'),
('MIDJAN102024-FIC00046', 'A Midsummer Night''s Dream', 'William Shakespeare', 1595, 'Drama', 'Available'),
('MUCHJAN102024-FIC00047', 'Much Ado About Nothing', 'William Shakespeare', 1598, 'Drama', 'Available'),
('TWELJAN102024-FIC00048', 'Twelfth Night', 'William Shakespeare', 1601, 'Drama', 'Available'),
('ASJAN102024-FIC00049', 'As You Like It', 'William Shakespeare', 1599, 'Drama', 'Available'),
('TAMJAN102024-FIC00050', 'The Taming of the Shrew', 'William Shakespeare', 1592, 'Drama', 'Available');

-- 7. Show success message
SELECT 'Database setup completed successfully!' as message;